### ISSUE TITLE
Not found:./resnet/checkpoints/resnet_v2_50.ckpt

### ISSUE THREAD

**Issue by emmra** [sthalles/deeplab_v3#14]
./resnet/checkpoints/resnet_v2_50.ckpt: Not found: ./resnet/checkpoints; No such file or directory

thinks very much

**Comment by sthalles** [comment]
check the README file. It is updated. Thanks.

**Comment by emmra** [comment]
Thinks




| |
郭伟
邮箱：guowei3158@126.com
|

签名由 网易邮箱大师 定制

On 04/19/2018 22:02, Thalles Silva wrote:

check the README file. It is updated. Thanks.
