### ISSUE TITLE
how to use my own data set which are not of the format of VOC

### ISSUE THREAD

**Issue by surfreta** [sthalles/deeplab_v3#16]
Hi, if the studied data set is not VOC data set. The training set just consists of a pair of raw images and corresponding mask images, how to transform these images into tfrecord that can be feed into your code?

Thanks.

![um_000003](https://user-images.githubusercontent.com/23064201/38950681-e1ba6c28-430b-11e8-9e11-48a958d3fb9b.png)

![um_lane_000003](https://user-images.githubusercontent.com/23064201/38950686-e63cedf2-430b-11e8-972d-bb57b6cc4991.png)

**Comment by sthalles** [comment]
Check out the dataset folder, there you will find a notebook you can tweak and create your tfrecords.

**Comment by Listen1007** [comment]
Hi.
just like @surfreta ,I have changed the code to generate tf.records, I have generate tf.records data successfully, but when I try run train.py ,it will return an error: 

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 66304 values, but the requested shape has 65536
how to fix this

 the code is:
`import tensorflow as tf
import numpy as np
import os
#import scipy.io as spio
#from matplotlib import pyplot as plt
from scipy.misc import imread, imresize

#from PIL import Image

base_dataset_dir_voc = './fw/'
images_folder_name_voc = "origin/"
annotations_folder_name_voc = "fw_lab/"
images_dir_voc = os.path.join(base_dataset_dir_voc, images_folder_name_voc)
annotations_dir_voc = os.path.join(base_dataset_dir_voc, annotations_folder_name_voc)
def get_files_list(base_dataset_dir, images_folder_name, annotations_folder_name, filename):
    images_dir = os.path.join(base_dataset_dir, images_folder_name)
    annotations_dir = os.path.join(base_dataset_dir, annotations_folder_name)

    file = open(filename, 'r')
    images_filename_list = [line for line in file]
    return images_filename_list


images_filename_list = get_files_list(base_dataset_dir_voc, images_folder_name_voc, annotations_folder_name_voc, "custom_train.txt")
print("Total number of training images:", len(images_filename_list))

np.random.shuffle(images_filename_list)
val_images_filename_list = images_filename_list[:int(0.10*len(images_filename_list))]
train_images_filename_list = images_filename_list[int(0.10*len(images_filename_list)):]

print("train set size:", len(train_images_filename_list))
print("val set size:", len(val_images_filename_list))



def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

TRAIN_DATASET_DIR="./fw/dataset/"
TRAIN_FILE = 'train.tfrecords'
VALIDATION_FILE = 'validation.tfrecords'
train_writer = tf.python_io.TFRecordWriter(os.path.join(TRAIN_DATASET_DIR,TRAIN_FILE))
val_writer = tf.python_io.TFRecordWriter(os.path.join(TRAIN_DATASET_DIR,VALIDATION_FILE))
def create_tfrecord_dataset(filename_list, writer):
    
    
    # create training tfrecord
    for i, image_name in enumerate(filename_list):
        image_np = imread(os.path.join(images_dir_voc, image_name.strip() + ".jpg"))
        annotation_np = imread(os.path.join(annotations_dir_voc, image_name.strip() + ".png"))
        
         
 
        image_h = image_np.shape[0]
        image_w = image_np.shape[1]
        #print("################",image_h,image_w)
        

        img_raw = image_np.tostring()
        annotation_raw = annotation_np.tostring()

        example = tf.train.Example(features=tf.train.Features(feature={
                'image_raw': _bytes_feature(img_raw),
                'annotation_raw': _bytes_feature(annotation_raw),
                'height': _int64_feature(image_h),
                'width': _int64_feature(image_w)}))
        

        writer.write(example.SerializeToString())
        
    print("End of TfRecord. Total of image written:", i)
    writer.close()

# create training tfrecord
create_tfrecord_dataset(train_images_filename_list, train_writer)

#  create validation dataset
create_tfrecord_dataset(val_images_filename_list, val_writer)`

**Comment by sthalles** [comment]
I have updated the code to use the newest TF version. Also, updated the CreateTfRecords.ipynb, please refer to the README.

**Comment by parachutel** [comment]
@Listen1007 I got the same issue as yours. Dimension error from reshape. 

@sthalles Did you generate your .tfrecord from pascal augmented VOC images (so that annotations came from .mat files)? I generated .tfrecord from the original VOC and the annotations are from .png files. Then I met the reshape error.

**Comment by Listen1007** [comment]
@parachutel @sthalles Me too. when don't use the mat files to generate , no matter VOC or our own data,  It will return reshape error

**Comment by sthalles** [comment]
Please, read the blog for more info. Regarding the reshape error. The code assumes that the annotation images are **single channel**. The VOC images annotations, originally are RGB. You should preprocess them before using. Try using the augmented Pascal set. Their annotation images come in the right shape.
