### ISSUE TITLE
IterationG

### ISSUE THREAD

**Issue by emmra** [sthalles/deeplab_v3#17]
tensorflow.python.framework.errors_impl.OutofRangeError: End of sequence

**Comment by emmra** [comment]
2018-04-15 15:28:51.709488: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:129] Shuffle buffer filled.
。。。。
  File "/disk1/g201708021059/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,513,513,3], [?,513,513], [?], [?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandle)]]

**Comment by lizhineng1018** [comment]
I have encountered the same problem as you, have you solved it? Looking forward to your reply!

**Comment by sthalles** [comment]
I have updated the code to use the newest TF version.
