### ISSUE TITLE
last feature dimension size inconsistency

### ISSUE THREAD

**Issue by iliadsouti** [sthalles/deeplab_v3#2]
Last feature has size (32x32) and there is a convolution with kernel size 3 with dilation rate 18. So in order that the feature map would be valid one the feature size should be (2*18+3 =39). Is that correct?

**Comment by sthalles** [comment]
Hello, assuming you are referring to the possibility of making an atrous conv behaves like a 1x1 conv, no. This only happens when the dilation rate is very close to the feature map's size. Most precisely, in this example it would happen for a dilation rate of 33. For more details see the Atrous Convolution section of [Semantic Segmentation with Deeplab-v3](https://sthalles.github.io/deep_segmentation_network/).

**Comment by iliadsouti** [comment]
According to tensorflow  documentation on [atrous convolution](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d), it acts like a normal convolution with filter size = (rate - 1) * 2 + 3. In the example provided in your blog (rate = 3), the size of feature map should be at least 7x7 [(3-1)*2+3]. I am guessing when the feature map has size 32x32 the atrous rate at most could be 14. Am I right?
TIA

**Comment by sthalles** [comment]
"According to tensorflow documentation on atrous convolution, it acts like a normal convolution with filter size = (rate - 1) * 2 + 3." That is correct. 

When the feature map size is 32x32 **to make an atrous conv behaves like a 1x1 conv,** you need a dilation rate of 33. And to make the atrous filter to fully cover the 32x32 feature map the atrous rate should be max of 15 (remember the gaps between the active cells in an atrous filter has size _atrous_rate-1=14_)

So, in the network, applying a atrous rate of 18 in a 32x32 feature map, **does NOT make it a 1x1 conv**. But the atrous filter does NOT cover the entire feature map as well.

Hope I could help.

**Comment by iliadsouti** [comment]
Thanks for your clarification. I understand now. However, I do have another question. That being said some of activation map resulted from convolution are actually comes from the padded region. To be exact when we use atrous rate 18 our effective filter height would be 37 (a normal convolution with filter size 37 applied on feature map 33). Which means only four value is taken from the original image and the rest (the other five) is from padded regions. Am I correct?
TIA

**Comment by iliadsouti** [comment]
I think I found my answer. 
Thanks
