### ISSUE TITLE
Using your model to train on a different dataset

### ISSUE THREAD

**Issue by srikantrao** [sthalles/deeplab_v3#22]
Hi 

I am instantiating your model from the checkpoint that you have provided and I am looking to add some additional layers to the end. 
I am using it in the following way:
```python
path = os.path.join(model_path, model_name)
    saver = tf.train.import_meta_graph(path + '.meta')
    graph = tf.get_default_graph()
    trained_output = graph.get_tensor_by_name("cond/DeepLab_v3/logits/Conv2D:0")
    final_conv_layer = tf.layers.conv2d(trained_output, num_classes, 1,
                                        kernel_regularizer=tf.contrib.layers.l2_regularizer(0.001),
                                        kernel_initializer=tf.truncated_normal_initializer(mean=0, stddev=0.01),
                                        name='final_conv_layer')
    final_layer = tf.image.resize_bilinear(final_conv_layer, image_shape, name='final_layer')
```
When I print out all the tensors in the network, I see that you have two placeholders called Placeholder(line:15 in output1.txt) and Placeholder_1(line:38 in output1.txt). 
Can you provide some info on what  each of these placeholders needs as an input ? 

The code that i used to look at the all the operation names is as follows: 
```python
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.restore(sess, save_path="./models/model.ckpt")
    op = sess.graph.get_operations()
    op_list = [m.name for m in op]
    for operation in op_list:
        print(operation)
```

I am attaching the output1.txt file which contains the names of the tensors and the .py file I use to generate it (deeplab_test.txt).
Thanks for your help!
[output1.txt](https://github.com/sthalles/deeplab_v3/files/2042883/output1.txt)
[deeplab_test.txt](https://github.com/sthalles/deeplab_v3/files/2042884/deeplab_test.txt)

P.S - Thanks for the medium article. It was helpful in understanding how DeepLab works.

**Comment by sthalles** [comment]
There are two placeholders. One for specifying the training/validation iterator handler, and another that specifies if model is in train or test mode.
