### ISSUE TITLE
shape mismatch

### ISSUE THREAD

**Issue by miriam124578** [sthalles/deeplab_v3#24]
When I am trying to train, I get the following error:

> 2018-07-15 22:31:21.210544: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 750000 values, but the requested shape has 187500
> [[Node: annotation_reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32](DecodeRaw_1, annotation_reshape/shape)]]

This seems to be related to the shape in tfrecord file. I used the code provided in the repository to create those files. Should I update them?

**Comment by CChape** [comment]
Hi, first thanks for sharing this works!
I have exactly the same problem. I wanted to train DeepLab , on the Ade20k dataset, I used the notebook provide to prepare the tfrecords. Is there any resize operation, or it's may be a cropsize problem?  


Thanks for the answers!

**Comment by sthalles** [comment]
Make sure you create the tfrecords in the correct way. The only thing I can say is that you are trying to reshape a tensor to the wrong shape.
