### ISSUE TITLE
NoneType error at CreateTfRecord

### ISSUE THREAD

**Issue by matheuscass** [sthalles/deeplab_v3#25]
I'm editing CreateTfRecord file so I can use my own dataset. When I run the last 2 cells I have the following error message "TypeError: 'NoneType' object is not iterable". I uploaded a text file with the whole thing.
[error.txt](https://github.com/sthalles/deeplab_v3/files/2207655/error.txt)

**Comment by sthalles** [comment]
You have to edit the notebook to suit your needs. Do you have a matlab file? because that is what the script is trying to do.

**Comment by matheuscass** [comment]
I fixed it already! Thanks! But I'm having another problem: when I run train.py, it fills the shuffle buffers and after that it does nothing else! Any ideas? =(

**Comment by matheuscass** [comment]
I'm trying to run it on my CPU. Do I have to edit the train.py file for that?

**Comment by sthalles** [comment]
no need.
