### ISSUE TITLE
 No module named 'grpc'

### ISSUE THREAD

**Issue by ccs1605** [sthalles/deeplab_v3#28]
when running the ```deeplab_client.ipynb``` notebook, i got  No module named 'grpc'.
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d5a48b32af91> in <module>()
      1 from __future__ import print_function
      2 from PIL import Image
----> 3 from grpc.beta import implementations
      4 import tensorflow as tf
      5 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'grpc'`
install both `$ python -m pip install grpcio
$ python -m pip install grpcio-tools`
but the problem remains.

**Comment by sthalles** [comment]
head to tensorflow serving doc and make sure the dependencies are all set.
