### ISSUE TITLE
Argument "resnet_model" missing in test.py

### ISSUE THREAD

**Issue by lukasliebel** [sthalles/deeplab_v3#3]
Hi and thanks for your well-written blog post and code!

I think I encountered a bug in the script for testing. Seems like the argument "resnet_model" is not available in [test.py](https://github.com/sthalles/deeplab_v3/blob/master/test.py). I'm currently on TF 1.5 so it might be related to this, but as far as I can tell from a quick glance through the code I think it's just a missing argument.

Calling the script as described in the README using:
> python test.py --model_id=16645

yields an error:
> resnet = getattr(resnet_v2, args.resnet_model)
> TypeError: getattr(): attribute name must be string

I was able to fix it by replacing all occurrences of `args.resnet_model` with `"resnet_v2_50"` (which is a horrible hack tbh), so I assume the argument is actually just missing in test.py atm.

Cheers
Lukas

**Comment by lukasliebel** [comment]
Oh, also the used GPU is hard-coded as `os.environ["CUDA_VISIBLE_DEVICES"]="3"` in test.py. Is there a special reason for this? Works fine for other values. Maybe `args.gpu_id `could be added along with `args.resnet_model`.

**Comment by sthalles** [comment]
Thanks for your comments and for pointing out the bug. 

It turns out that `"resnet_model": "resnet_v2_50"` was missing from the data.json file. I uploaded the new data.json.

Regarding the `os.environ["CUDA_VISIBLE_DEVICES"]="3"` I will remove it from the test.py file. It really does not make sense to be there.

**Comment by lukasliebel** [comment]
Wow, that was an impressively quick response and fix, thank you!

As a side-comment, calling the test script as `CUDA_VISIBLE_DEVICES=X python test.py --model_id=16645` with `X` being the GPU ID of choice might still be desirable in certain setups (_e.g._ assigning a specific GPU for testing while others train). So it might still be worth considering adding this argument.
