### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by VanitarNordic** [sthalles/deeplab_v3#34]
is it possible to fine tune the model on a custom dataset which might have different number of classes?

of course a pre-trained weights file must exist either

**Comment by sthalles** [comment]
Yes, you can fine-tune to a different task. Just change the number of classes parameter and feed in the new dataset.

**Comment by sthalles** [comment]
In the paper, they perform some additional (training procedures) that I did not do here. They pre-train the model on COCO and also perform inference with output stride of 8.
