### ISSUE TITLE
Retrain with checkpoints files

### ISSUE THREAD

**Issue by kmbmjn** [sthalles/deeplab_v3#35]
Thanks for great work.
I found that checkpoints files were written successfully. I used these files with test.py to load the saved model.
On the other hand, I want to know whether I could load the saved checkpoints files for retraining.

**Comment by sthalles** [comment]
Sure, just point the "restorer.restore(sess, "./resnet/checkpoints/" + args.resnet_model + ".ckpt")" line to your checkpoints file.

**Comment by kmbmjn** [comment]
@sthalles I found that your suggestion works properly. Thanks!
