### ISSUE TITLE
A question about the inference

### ISSUE THREAD

**Issue by kmbmjn** [sthalles/deeplab_v3#38]
Thanks for great work.
I have a question about the inference.
In the original Deeplab_v3 paper, there are some comments about running inferences with Cityscapes dataset. They said "We adopt the same training protocol as before except that we employ 90K training iterations, crop size equal to 769, **and running inference on the whole image, instead of on the overlapped regions as in [11].**"
I found that running the codes in this repository produces the inference results with the cropped size(513x513). I want to know whether I could also run inference on the whole image, using the model trained on the cropped images.

**Comment by sthalles** [comment]
yes, if you remove the "scale_image_with_crop_padding" from test.py you will do just that.
