### ISSUE TITLE
Could add datasets download link in other free online drives?

### ISSUE THREAD

**Issue by PeterXiaoGuo** [sthalles/deeplab_v3#4]
Thanks for this great share! 

When I attempt to download the datasets, it's in a drive called MEGA, and it sets many barriers to download this datasets.... after several hours, I'm waiting for the free quota during the download process.

Could you please consider to make a copy of datasets to google drive or other free online drives? 

Thank you very much,
Xiao

**Comment by sthalles** [comment]
Hello,

I can upload the files to another driver, however, it may take a few hours. I hope you could download the files already. Let me know.

Thanks.
