### ISSUE TITLE
version of tensorflow

### ISSUE THREAD

**Issue by whulc** [sthalles/deeplab_v3#5]
Can this project run at lower version TensorFlow？

**Comment by sthalles** [comment]
Hello, 

I haven't tried running it in a lower version. I can only guarantee the version stated in the README.

Thanks.

**Comment by whulc** [comment]
Thank you for your timely response.  The dilated convolution is added to cudnn from v6.0, Does that mean I should use higher version of cudnn than 6.0 ?

**Comment by sthalles** [comment]
TF 1.4 (the version used in this project) uses CUDA 8 and cuDNN 6. So, I would advise to use these versions or higher ones.
