### ISSUE TITLE
Which paper is this repo an implementation of? 

### ISSUE THREAD

**Issue by tadbeer** [sthalles/deeplab_v3#8]
Up till now 4 editions of DeepLabs papers have been released.
The blog post mentions the paper no. 1706.05587, while the repo Read-me mentions the previous edition numbered 1606.00915. 
Which edition of DeepLab is the implementation in this repo based on?
I am aiming to train on my custom dataset and want to refer to the paper to get a better understanding of your implementation.

**Comment by sthalles** [comment]
Hello, 

I haven't noticed this issue with the references. It is fixed. Thanks for contributing.
